log:
  level: DEBUG

api:
  dashboard: true

accessLog: {}

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/
    watch: true

entryPoints:
  web:
    address: ":4000"

http:
  routers:
    django:
      service: django
      rule: >
        PathPrefix(`/`) ||
        PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/api`) || PathPrefix(`/django`)
      entryPoints:
        - web
    react:
      service: react
      rule: "PathPrefix(`/app`) "
      entryPoints:
        - web
  middlewares:
    csrf:
      # https://doc.traefik.io/traefik/master/middlewares/http/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]
  services:
    react:
      loadBalancer:
        servers:
          - url: "http://react:5173"
    django:
      loadBalancer:
        servers:
          - url: "http://django:8000"
